version: 0.2

phases:
  install:
    commands:
      - echo "Installing Helm..."
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
  build:
    commands:
      # generate secrets
      - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id cba_demo_app_secrets --query SecretString --output text)
      - |
        cat <<EOF > secrets.yml
        apiVersion: v1
        kind: Secret
        metadata:
          name: spree-ecomm-secrets
          namespace: spree-ecomm
        data:
        EOF
      - |
        echo "$SECRET_JSON" | jq -r 'to_entries[] | "\(.key): \(.value | @base64)"' | while IFS=: read key value; do
          echo "  $key: $value" >> secrets.yml
        done
      - cp secrets.yml helm/templates/
     # Package helm release
      - echo "Packaging the Helm chart..."
      - helm package helm
      - |
        if [[ -z $(helm list | grep spree-ecomm) ]]; then
          helm install spree-ecomm spree-ecomm-0.1.tgz
        else
          helm upgrade spree-comm --dry-run
          helm upgrade spree-comm
        fi
