apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameSpace }}-deployment
  namespace: {{ .Values.nameSpace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spree
  template:
    metadata:
      labels:
        app: spree
    spec:
      containers:
        - name: spree-webapp
          image: {{ .Values.image.url }}
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_MAX_THREADS
              value: "{{ .Values.rails.maxThreads }}"

            - name: RAILS_ENV
              value: "{{ .Values.rails.env }}"

            - name: DB_NAME
              value: "{{ .Values.db.database }}"

            - name: DB_HOST
              value: "{{ .Values.db.host }}"

            - name: DB_USER
              value: "{{ .Values.db.user }}"

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: spree-ecomm-secrets
                  key: DB_PASS

            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: spree-ecomm-secrets
                  key: SECRET_KEY_BASE

            - name: REDIS_URL
              value: "{{ .Values.redisUrl }}"

            - name: AWS_REGION_S3
              value: "{{ .Values.assetsS3.region }}"

            - name: ASSETS_S3_BUCKET
              value: "{{ .Values.assetsS3.bucket }}"

            - name: AWS_ACCESS_KEY_ID_S3
              valueFrom:
                secretKeyRef:
                  name: spree-ecomm-secrets
                  key: AWS_ACCESS_KEY_ID_S3

            - name: AWS_SECRET_ACCESS_KEY_S3
              valueFrom:
                secretKeyRef:
                  name: spree-ecomm-secrets
                  key: AWS_SECRET_ACCESS_KEY_S3

        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
