apiVersion: v1
kind: Service
metadata:
  labels:
    app: spree
  name: {{ .Values.nameSpace }}-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: spree
  type: NodePort
